glotaran/pyglotaran-examples

.github/dependabot.yml
.github/workflows/autoupdate-pre-commit-config.yml
.pre-commit-config.yaml

Having an up to date `.pre-commit-config.yaml` reduces the number of venvs we need to have locally since `pyglotaran` also updates its config. (run `pre-commit gc` to remove unused venvs)

🔧Update pre-commit config

---

.github/workflows/integration_test.yml
.gitignore
action.yml
requirements.txt
scripts/run_examples.py

To make running all examples (e.g. for a stability check of the `pyglotaran` API) as easy as possible it is nice to run them via a CLI. Also, making them run headless (no plots popping up and taking focus all the time) is a nice to have feature.
The CLI can be run by:
```console
python scripts/run_examples.py [--headless] <example_name>
```
To run all examples use:
```console
python scripts/run_examples.py [--headless] run-all
```
When run in headless mode, all plots will be saved in a single pdf per test in the folder `plot_results`.
In addition to the CLI this PR adds a [composite action](https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/) which can be used as integration tests `pyglotaran` and maybe `pyglotaran-extras`.
As an internal test it also adds a …

Run examples by a CLI

---

.github/workflows/integration_test.yml
action.yml
scripts/run_examples.py

The action added by #13 did only properly work with `workflow_dispatch` but failed with `push` and `pull_request` events.
The reason for this was that `github.event.inputs.pyglotaran_examples_branch` was only set on `workflow_dispatch` and other events didn't use its default. 
This is why
```
git clone --depth 1 -b ${{ inputs.examples_branch }} https://github.com/glotaran/pyglotaran-examples.git
```
evaluated to
```
git clone --depth 1 -b https://github.com/glotaran/pyglotaran-examples.git
```
and git did throw an error because there wasn't a repo to clone provided.
Now the action checks that either `inputs.examples_branch` is provided or that a folder `pyglotaran-examples` exists.
If none of those conditions are met it raises an error explaining whats needs to be done.
The workflow now …

🩹Fix action

---

.github/workflows/autoupdate-pre-commit-config.yml

Reverts glotaran/pyglotaran-examples#11
Let's keep it `v2`, since `v2.1.4` has some issues https://github.com/actions/cache/issues/528
`v2` now points at `v2.1.5` which doesn't have known bugs.

Revert "Bump actions/cache from v2 to v2.1.4"

---

.github/workflows/autoupdate-pre-commit-config.yml

This is in favor of pre-commit-ci doing it.

🚇 Remove schedule from "Update pre-commit config" workflow

---

requirements.txt

That way the tagged version is really frozen in time and won't change behavior until we can use the pinned pypi version of pyglotaran-extras.
For the existing v0.3.3 tag we have two option:
1. Delete it and create a new one (it currently isn't used as far as we know anyway)
2. Create a new tag (e.g. with [pythonic naming](https://www.python.org/dev/peps/pep-0440/) `v0.3.3.post1`)
After this PR got merged we should create/update the tag and then we can revert it again.

🩹 Pin the installed version of pyglotaran-extras to use a git sha

---

requirements.txt

Reverts glotaran/pyglotaran-examples#29
After recreating the tag we can unpin `pyglotaran-extras` again.

Revert "🩹 Pin the installed version of pyglotaran-extras to use a git sha"

---

.github/workflows/update_compare_results.yml
pyglotaran_examples/ex_spectral_constraints/ex_spectral_constraints.py
pyglotaran_examples/quick_start/quickstart.py
pyglotaran_examples/study_fluorescence/target_analysis_script.py
pyglotaran_examples/test/simultaneous_analysis_3d_disp/sim_analysis_script_3d_disp.py
pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/sim_analysis_script_3d.py
pyglotaran_examples/test/simultaneous_analysis_3d_weight/sim_analysis_script_3d_weight.py
pyglotaran_examples/test/simultaneous_analysis_6d_disp/sim_analysis_script_6d_disp.py

Limiting the `maximum_number_function_evaluations` will make the results more deterministic and allow us to compare new results with a "gold standard" we set (e.g. `0.4.0`).
To update that "gold standard" I added a workflow that we can manually trigger by `workflow_dispatch` to create new results and upload them to the branch `comparison-results` which only contains the results.
This branch can then be used by the `pyglotaran` CI to validate result consistency.
I didn't change the `maximum_number_function_evaluations` for the cases in `pyglotaran_examples/test` (currently 99) , maybe you have an idea for sensible values.
E.g. we could fix them to the `maximum_number_function_evaluations` it took them to converge with `pyglotaran==0.4.0` as I did for the other cases.

🧪 Fix number of 'maximum_number_function_evaluations'

---

.github/workflows/update_compare_results.yml

Right now the "Update comparison results" workflow would clutter and grow indefinitely, this PR changes it to clean up after itselfe.

👌 Refined comparison-result updates to remove obsolete results

---

scripts/run_examples.py

Currently, when running `python scripts/run_examples.py run-all --headless` the plots aren't created in-between example runs, which results in ever-growing pdf sizes and duplication of the plots.
This PR changes the behavior to clear out **after** they were saved to PDF, reducing the size of `plot_results` from 117MB to 20MB. As a side-effect running the examples all together should also be faster.

🩹 Fix already saved plots being appended to each pdf

---

scripts/run_examples.py

Follow-up PR for #38, where the duplicate plots were removed but empty pages were still added.
By using `plt.close(fig)` the old figures will be removed from `plt.get_fignums()`, so only the intended plots get added to the summary PDF.

🩹 Fix adding empty pages to PDF

---

.github/workflows/update_compare_results.yml
action.yml

For proper reproducibility, we need to know the exact versions (git commit) of `pyglotaran` and `pyglotaran-examples` that produced the results.
This PR changes the action and "Update comparison results" workflow to extract the commit shas and save them to file as well as the commit message of commits on the `comparison-results` branch.
I also cleaned out the commits on the `comparison-results` branch, since they weren't reproducible due to the missing information.
This is [an example commit](https://github.com/s-weigand/pyglotaran-examples/commit/e1a586082c83f114c0e7233aeb113626ed478b6b) to the empty `comparison-results` branch on my fork.

👌 Refine action and "Update comparison results" workflow for reproducibility

---

.github/workflows/integration_test.yml
.github/workflows/update_compare_results.yml
action.yml
scripts/run_examples.py

Currently, the examples action requires manually defining a list of example names to run them in a parallel matrix style.
While this is fine for this repository by itself, we also need to synchronize the list of available examples across all our repositories that use this action.
This might lead to errors if examples get removed or a lower coverage if new examples aren't added.
The changes in this PR allow the action to generate a list of all available examples in one job, which can then be used to define the matrix for the job that runs the examples (see updated workflows).
- [✨ Added function to set example names as output in gh actions](https://github.com/glotaran/pyglotaran-examples/commit/59d9c192c20108854faa4cce3de595317bf41bc4)
- [♻️ Moved all 3rd party imports beside yaargh inside …

🚇👌 Make action self managed

---

scripts/run_examples.py

This is a hotfix to allow us to update the "gold standard" which [currently fails for DOAS due to too big files (over 100MB)](https://github.com/glotaran/pyglotaran-examples/runs/5711532975?check_suite_focus=true).
This reduces file since to ~2/3 (at least for the DOAS `104MB` -> `64MB`).
Later we should add this as a proper argument for `save_result` and the netCDF plugin in `pyglotaran` itself.
- [👌🚇 Write all result files with zlib compression activated](https://github.com/glotaran/pyglotaran-examples/commit/5b5c8656e4f45b9cd8877ef1a24134e26d3b77b7)

👌🚇 Write all result files with zlib compression activated

---

pyglotaran_examples/ex_two_datasets/ex_two_datasets.py

This is needed for https://github.com/glotaran/pyglotaran/pull/1060 to pass the result comparison with `ex_two_datasets` which now needs more function evaluation to fully converge.
The reason for the additionally needed function evaluation will be investigated later
- [♻️ Raised maximum_number_function_evaluations of ex_two_datasets from 15 to 18](https://github.com/glotaran/pyglotaran-examples/commit/b6657f2d492ebd41b7cc5362d5641822949787d5)

♻️ Raised maximum_number_function_evaluations of ex_two_datasets from 15 to 18

---

pyglotaran_examples/ex_doas_beta/ex_doas_beta.py
pyglotaran_examples/ex_doas_beta/ex_doas_beta_ascii.py
pyglotaran_examples/ex_doas_beta/models/model.yml
pyglotaran_examples/ex_spectral_constraints/ex_spectral_constraints.py
pyglotaran_examples/ex_spectral_constraints/models/model.yml
pyglotaran_examples/ex_spectral_constraints/models/model_equal_area_penalties.yml
pyglotaran_examples/ex_spectral_guidance/ex_spectral_guidance.py
pyglotaran_examples/ex_spectral_guidance/models/model_guidance.yml
pyglotaran_examples/ex_two_datasets/ex_two_datasets.py
pyglotaran_examples/ex_two_datasets/models/model.yml
pyglotaran_examples/quick_start/model.yml
pyglotaran_examples/quick_start/quickstart.py
pyglotaran_examples/study_fluorescence/models/model-target.yaml
pyglotaran_examples/study_fluorescence/models/model.yaml
pyglotaran_examples/study_fluorescence/target_analysis_script.py
pyglotaran_examples/study_transient_absorption/models/model.yml
pyglotaran_examples/study_transient_absorption/models/model_2d_co_co2.yml
pyglotaran_examples/study_transient_absorption/target_analysis_script.py
pyglotaran_examples/study_transient_absorption/two_dataset_analysis.py
pyglotaran_examples/test/simultaneous_analysis_3d_disp/model.yml
pyglotaran_examples/test/simultaneous_analysis_3d_disp/sim_analysis_script_3d_disp.py
pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/model.yml
pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/sim_analysis_script_3d.py
pyglotaran_examples/test/simultaneous_analysis_3d_weight/model.yml
pyglotaran_examples/test/simultaneous_analysis_3d_weight/sim_analysis_script_3d_weight.py
pyglotaran_examples/test/simultaneous_analysis_6d_disp/model.yml
pyglotaran_examples/test/simultaneous_analysis_6d_disp/sim_analysis_script_6d_disp.py
scripts/run_examples.py

This upgrades the model files to use the pyglotaran `0.5.0` syntax and the script files to use the pyglotaran-extras `0.5.0rc1` syntax.
Best reviewed commit by commit.
All deprecations up to the [current main of pyglotaran](https://github.com/glotaran/pyglotaran/commit/69bb7dc066539c21192465a8df5d5b6df5c01fc1) were removed.

🩹🗑️ Fixed usage of deprecated functionality and syntax

---

pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/model.yml
pyglotaran_examples/test/simultaneous_analysis_3d_weight/model.yml

This removes the improper usage of `spectral-multi-gaussian` IRF without dispersion and changes it to a `gaussian` IRF.
The validation in https://github.com/glotaran/pyglotaran/pull/1135 is a lot stricter and prohibits wrong usage (model crash).
- [🩹 Changed 'spectral-multi-gaussian' to 'gaussian' if no dispersion is used](https://github.com/glotaran/pyglotaran-examples/commit/a61448fbbbff4cf8f91a85a24e0a13515ca65a0a)

👌 Change 'spectral-multi-gaussian' to 'gaussian' if no dispersion is used

---

action.yml
scripts/run_examples.py

GitHub deprecated the usage of `set-output` in favor of using the environment file located at `$GITHUB_OUTPUT`.
The old syntax already gives warnings and will be switched off 31st May 2023.
This change makes the CI more future proof.
Ref.: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- [♻️ Upgraded github action output setting](https://github.com/glotaran/pyglotaran-examples/commit/b3f67d050a65d9c73e4f0f2aa603fb9323bb57e0)

♻️🚇 Use GITHUB_OUTPUT instead of set-output in github actions

---

.github/workflows/integration_test.yml

This change adds steps to the CI that upload the `comparison-results` as release artifact on a release.
[See my fork for an example release](https://github.com/s-weigand/pyglotaran-examples/releases/tag/v-asset-upload-test)
- [🚇🚀 Add steps to upload release assets](https://github.com/glotaran/pyglotaran-examples/commit/c18959cb6a99656cc57eb3e22d222956ce34ce3b)
- [🚇🚀 Tag comparison-results branch on release](https://github.com/glotaran/pyglotaran-examples/commit/0d7cbc8a171b2a198d4942414f4e726ee3e2de47)
- [👌🚇 Factor out release steps into seperate job](https://github.com/glotaran/pyglotaran-examples/commit/08c2d4e4ca2d44d55280f7c3938b1239367771e6)
- [👌 Exclude .git folder](https://github.com/glotaran/pyglotaran-examples/commit/1bcabaaf961c5c4dc8505623764b541869412259)
- [🩹 Manually create …

🚇 Upload comparison-results as asset on release

---

.pre-commit-config.yaml

To be compatible with the [bugfix of coherent artifacts using the same clp_labels for all megacomplexes](https://github.com/glotaran/pyglotaran/pull/1292) we need to change the (data used in) comparison results.
Specifically, the (labels in) dataset ex_doas_beta/target_analysis/dataset1.nc need updating.
I used the following code to update the cpl_labels for the coherent artifact in the ex_doas_beta case study.
```py
from glotaran.io import load_dataset, save_dataset
data_path = "ex_doas_beta/target_analysis/dataset1.nc"
data = load_dataset(data_path)
new_clps = []
for val in data.coords["clp_label"].values:
if val.startswith("coherent_artifact"):
val = f'{val}_artifact'
new_clps.append(val)
new_clps
new_data = data.assign_coords(clp_label=new_clps)
save_dataset(new_data, data_path, …
```

🚧🩹 Suffix ex_doas_beta CA clp_labels with megcomplex name (_artifact)

---

.pre-commit-config.yaml
.ruff-notebooks.toml
.ruff.toml
pyglotaran_examples/ex_doas_beta/ex_doas_beta.ipynb
pyglotaran_examples/ex_spectral_constraints/ex_spectral_constraints.ipynb
pyglotaran_examples/ex_spectral_constraints/models/scheme_equal_area_penalties.yml
pyglotaran_examples/ex_spectral_guidance/ex_spectral_guidance.ipynb
pyglotaran_examples/ex_two_datasets/ex_two_datasets.ipynb
pyglotaran_examples/study_fluorescence/global_and_target_analysis.ipynb
pyglotaran_examples/study_transient_absorption/models/scheme_2d_co_co2.yml
pyglotaran_examples/study_transient_absorption/target_analysis.ipynb
pyglotaran_examples/study_transient_absorption/two_dataset_analysis.ipynb
pyglotaran_examples/test/simultaneous_analysis_3d_disp/scheme.yml
pyglotaran_examples/test/simultaneous_analysis_3d_disp/sim_analysis_script_3d_disp.ipynb
pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/scheme.yml
pyglotaran_examples/test/simultaneous_analysis_3d_nodisp/simultaneous_analysis_3d_nodisp.ipynb
pyglotaran_examples/test/simultaneous_analysis_3d_weight/simultaneous_analysis_3d_weight.ipynb
pyglotaran_examples/test/simultaneous_analysis_6d_disp/simultaneous_analysis_6d_disp.ipynb

This PR fixes some errors discovered in the ports of examples for staging (introduced in #101).
- [🩹 Fix wrong weight for study_transient_absorption 2d_co_co2](https://github.com/glotaran/pyglotaran-examples/commit/a0c2ad0083cd3ff38445cda213f363d4fc8db757)
- [🩹 Fix s2 not varied in ex_spectral_constraints](https://github.com/glotaran/pyglotaran-examples/commit/dc63c0b803de6f983892412a83d25f678c3bcde8)

🩹 Fix bad ports
